#!/bin/sh
# UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity. -Dennis Ritchie
########################################################################################################################
#                               _____ __                         _____      
#        _  ______  _________  / __(_) /__     _________  ____  / __(_)___ _
#       | |/_/ __ \/ ___/ __ \/ /_/ / / _ \   / ___/ __ \/ __ \/ /_/ / __ `/
#    _ _>  </ /_/ / /  / /_/ / __/ / /  __/  / /__/ /_/ / / / / __/ / /_/ / 
#   (_)_/|_/ .___/_/   \____/_/ /_/_/\___/   \___/\____/_/ /_/_/ /_/\__, /  
#         /_/                                                      /____/   
#
########################################################################################################################
# 
#   An xprofile file, ~/.xprofile and /etc/xprofile, allows you to execute commands at the
#   beginning of the X user session - before the window manager is started.  The xprofile
#   file is similar in style to xinitrc.
#   
#	How this file is called:
#
# ┌───────────────┐
# │	Start X       ┝━━━━━━━━━━━━━/home/root/xinitrc
# └─┰─────────────┘
#   ┃ ┌─────────────────┐
#   ┗━┥ Display Manager ┝━━━━━━━/etc/lightdm/Xsession
#     └┰────────────────┘		
#      ┃ ┌────────────────┐
#      ┣━┥ Load Profiles  ┝━━━┳━━━/etc/ profile
#      ┃ └────────────────┘   ┣━$HOME/ .profile
#      ┃                      ┣━━━/etc/xprofile    			
#      ┃                      ┃ ╔═══════════════════╗           ┌──────────────┐
#      ┃                      ┗━╢ $HOME/.xprofile   ║	 <━━━━━━┥ You are here │
#      ┃                        ╚╤══════════════════╝           └──────────────┘
#      ┃                         ┗━$HOME/.config/X11/xprofile.d/*
#      ┃                            ┣━10-generate-xresources
#      ┃                            ┣━10-xrandr
#      ┃                            ┣━20-merge-xresources
#      ┃                            ┣━25-export-xresources-to-env
#      ┃                            ┣━30-set-background
#      ┃                            ┣━40-policy-kit
#      ┃                            ┣━50-compton
#      ┃                            ┗━60-setxkbmap
#      ┃ ┌────────────────┐ 					   					
#      ┣━┥ Load Resources ┝━━━┳━/etc/X11/Xresources
#      ┃ └────────────────┘	  ┗━$HOME/.Xresources
#      ┃                         ┗━$HOME/.config/X11/Xresources.d/*
#      ┃                            ┣━10-fonts.Xresources
#      ┃                            ┣━20-colors
#      ┃                            ┣━30-terminal-termite
#      ┃                            ┣━30-terminal-urxvt
#      ┃                            ┣━40-launcher-dmenu
#      ┃                            ┗━40-launcher-rofi
#      ┃ ┌────────────────┐
#      ┣━┥ Load Keymaps   ┝━━━┳━/etc/X11/Xkbmap
#      ┃ └────────────────┘   ┣━━━$HOME/.Xkbmap
#      ┃                      ┣━/etc/X11/Xmodmap
#      ┃                      ┗━━━$HOME/.Xmodmap
#      ┃ ┌────────────────┐
#      ┣━┥ System Scripts ┝━━━━━/etc/X11/xinit/xinitrc.d/*
#      ┃ └────────────────┘
#      ┃ ┌────────────────┐
#      ┗━┥ User Xsession  ┝━━━━━$HOME/.xsession
#        └────────────────┘
#
########################################################################################################################
#
#   References
#
#   Arch wiki 					https://wiki.archlinux.org/index.php/xprofile
#
#   Example Dotfiles
#		* github / kelsin		https://gist.github.com/kelsin/9460845
#
########################################################################################################################

#echo ".xprofile run" >> ~/.xsession-errors

#export XPROFILE_RUN=$(date +%s)

#set -o nounset
#set -o errexit

# Run all scripts in ~/.config/X11/Xsession.d
SESSIONS="$HOME/.config/X11/xprofile.d"
if [ -d "$SESSIONS" ]; then
  for SESSION in "$SESSIONS"/*; do
	#echo "$SESSION" >> ~/.xsession-errors 
	source $SESSION
  done
fi

#echo ".xprofile completed" >> ~/.xsession-errors
########################################################################################################################
# Need to review
########################################################################################################################

# ENV Variables
#export PATH="$HOME/.cabal/bin:$HOME/bin:$PATH"

# X Settings
#xrdb -load ~/.Xresources
#xsetroot -cursor_name left_ptr
#xmodmap ~/.Xmodmap

# No Beep
#xset b 0

# Hide Mouse Pointer
#unclutter -idle 2 -jitter 10 &

# Background
#sh ~/.fehbg

# Urxvt daemon
#urxvtd -q -o -f



########################################################################################################################
#	[-|\||) ()|= |_||\|[-
########################################################################################################################
